// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_operations.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingDeliveries = `-- name: CountPendingDeliveries :one
SELECT COUNT(*) FROM deliveries WHERE status = 'pending'
`

func (q *Queries) CountPendingDeliveries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingDeliveries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeliveriesForEvent = `-- name: CreateDeliveriesForEvent :many
INSERT INTO deliveries (event_id, endpoint_id, status, attempt_count, next_retry_at)
SELECT $1, endpoints.id, 'pending', 0, NOW()
FROM endpoints
WHERE endpoints.active = TRUE
  AND endpoints.topics && $2
ON CONFLICT (event_id, endpoint_id) DO NOTHING
RETURNING id, event_id, endpoint_id, status, attempt_count, next_retry_at,
          last_http_status, last_error, last_attempted_at, delivered_at, dead_lettered_at, created_at
`

type CreateDeliveriesForEventParams struct {
	EventID uuid.UUID `json:"event_id"`
	Topics  []string  `json:"topics"`
}

func (q *Queries) CreateDeliveriesForEvent(ctx context.Context, arg CreateDeliveriesForEventParams) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, createDeliveriesForEvent, arg.EventID, arg.Topics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.LastHttpStatus,
			&i.LastError,
			&i.LastAttemptedAt,
			&i.DeliveredAt,
			&i.DeadLetteredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (event_id, endpoint_id, status, attempt_count, next_retry_at)
VALUES ($1, $2, 'pending', 0, NOW())
RETURNING id, event_id, endpoint_id, status, attempt_count, next_retry_at,
          last_http_status, last_error, last_attempted_at, delivered_at, dead_lettered_at, created_at
`

type CreateDeliveryParams struct {
	EventID    uuid.UUID `json:"event_id"`
	EndpointID uuid.UUID `json:"endpoint_id"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.EventID, arg.EndpointID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastHttpStatus,
		&i.LastError,
		&i.LastAttemptedAt,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryByEventAndEndpoint = `-- name: GetDeliveryByEventAndEndpoint :one
SELECT id, event_id, endpoint_id, status, attempt_count, next_retry_at,
       last_http_status, last_error, last_attempted_at, delivered_at, dead_lettered_at, created_at
FROM deliveries
WHERE event_id = $1 AND endpoint_id = $2
`

type GetDeliveryByEventAndEndpointParams struct {
	EventID    uuid.UUID `json:"event_id"`
	EndpointID uuid.UUID `json:"endpoint_id"`
}

func (q *Queries) GetDeliveryByEventAndEndpoint(ctx context.Context, arg GetDeliveryByEventAndEndpointParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByEventAndEndpoint, arg.EventID, arg.EndpointID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastHttpStatus,
		&i.LastError,
		&i.LastAttemptedAt,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, event_id, endpoint_id, status, attempt_count, next_retry_at,
       last_http_status, last_error, last_attempted_at, delivered_at, dead_lettered_at, created_at
FROM deliveries
WHERE id = $1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastHttpStatus,
		&i.LastError,
		&i.LastAttemptedAt,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingDeliveriesForWorker = `-- name: GetPendingDeliveriesForWorker :many
SELECT id, event_id, endpoint_id, status, attempt_count, next_retry_at,
       last_http_status, last_error, last_attempted_at, delivered_at, dead_lettered_at, created_at
FROM deliveries
WHERE status = 'pending' AND next_retry_at <= NOW()
ORDER BY next_retry_at ASC, id ASC
LIMIT $1
`

// Ready pending deliveries for worker queue processing.
func (q *Queries) GetPendingDeliveriesForWorker(ctx context.Context, limit int32) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, getPendingDeliveriesForWorker, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.LastHttpStatus,
			&i.LastError,
			&i.LastAttemptedAt,
			&i.DeliveredAt,
			&i.DeadLetteredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryAttempt = `-- name: UpdateDeliveryAttempt :one
UPDATE deliveries
SET status = $1,
    attempt_count = attempt_count + 1,
    last_http_status = $2,
    last_error = $3,
    last_attempted_at = NOW(),
    next_retry_at = $4,
    delivered_at = $5,
    dead_lettered_at = $6
WHERE id = $7
RETURNING id, event_id, endpoint_id, status, attempt_count, next_retry_at,
          last_http_status, last_error, last_attempted_at, delivered_at, dead_lettered_at, created_at
`

type UpdateDeliveryAttemptParams struct {
	Status         string             `json:"status"`
	LastHttpStatus *int32             `json:"last_http_status"`
	LastError      pgtype.Text        `json:"last_error"`
	NextRetryAt    time.Time          `json:"next_retry_at"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	DeadLetteredAt pgtype.Timestamptz `json:"dead_lettered_at"`
	ID             uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateDeliveryAttempt(ctx context.Context, arg UpdateDeliveryAttemptParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryAttempt,
		arg.Status,
		arg.LastHttpStatus,
		arg.LastError,
		arg.NextRetryAt,
		arg.DeliveredAt,
		arg.DeadLetteredAt,
		arg.ID,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EndpointID,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastHttpStatus,
		&i.LastError,
		&i.LastAttemptedAt,
		&i.DeliveredAt,
		&i.DeadLetteredAt,
		&i.CreatedAt,
	)
	return i, err
}
