// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoint_management.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :one
INSERT INTO endpoints (name, url, topics, secret, active, max_attempts, timeout_ms)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, url, topics, secret, active, max_attempts, timeout_ms,
          circuit_state, failure_count, last_failure_at, cooldown_until,
          created_at, updated_at
`

type CreateEndpointParams struct {
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	Topics      []string    `json:"topics"`
	Secret      pgtype.Text `json:"secret"`
	Active      bool        `json:"active"`
	MaxAttempts int32       `json:"max_attempts"`
	TimeoutMs   int32       `json:"timeout_ms"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, createEndpoint,
		arg.Name,
		arg.Url,
		arg.Topics,
		arg.Secret,
		arg.Active,
		arg.MaxAttempts,
		arg.TimeoutMs,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const getEndpointByID = `-- name: GetEndpointByID :one
SELECT id, name, url, topics, secret, active, max_attempts, timeout_ms,
       circuit_state, failure_count, last_failure_at, cooldown_until,
       created_at, updated_at
FROM endpoints
WHERE id = $1
`

func (q *Queries) GetEndpointByID(ctx context.Context, id uuid.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByID, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointByName = `-- name: GetEndpointByName :one
SELECT id, name, url, topics, secret, active, max_attempts, timeout_ms,
       circuit_state, failure_count, last_failure_at, cooldown_until,
       created_at, updated_at
FROM endpoints
WHERE name = $1
`

func (q *Queries) GetEndpointByName(ctx context.Context, name string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointByName, name)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveEndpointsByTopics = `-- name: ListActiveEndpointsByTopics :many
SELECT id, name, url, topics, secret, active, max_attempts, timeout_ms,
       circuit_state, failure_count, last_failure_at, cooldown_until,
       created_at, updated_at
FROM endpoints
WHERE active = TRUE AND topics && $1
ORDER BY id
`

func (q *Queries) ListActiveEndpointsByTopics(ctx context.Context, topics []string) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listActiveEndpointsByTopics, topics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Topics,
			&i.Secret,
			&i.Active,
			&i.MaxAttempts,
			&i.TimeoutMs,
			&i.CircuitState,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, name, url, topics, secret, active, max_attempts, timeout_ms,
       circuit_state, failure_count, last_failure_at, cooldown_until,
       created_at, updated_at
FROM endpoints
WHERE (
    NOT $1::bool OR active = TRUE
)
AND (
    cardinality($2::text[]) IS NULL
    OR cardinality($2::text[]) = 0
    OR topics && $2::text[]
)
AND (
    $3::uuid IS NULL
    OR id > $3::uuid
)
ORDER BY id
LIMIT $4
`

type ListEndpointsParams struct {
	ActiveOnly bool        `json:"active_only"`
	Topics     []string    `json:"topics"`
	CursorID   pgtype.UUID `json:"cursor_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints,
		arg.ActiveOnly,
		arg.Topics,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Endpoint
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Topics,
			&i.Secret,
			&i.Active,
			&i.MaxAttempts,
			&i.TimeoutMs,
			&i.CircuitState,
			&i.FailureCount,
			&i.LastFailureAt,
			&i.CooldownUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEndpointDeliveryFailure = `-- name: MarkEndpointDeliveryFailure :one
UPDATE endpoints
SET failure_count = failure_count + 1,
    last_failure_at = NOW(),
    circuit_state = CASE
        WHEN failure_count + 1 >= $1 THEN 'open'
        ELSE circuit_state
    END,
    cooldown_until = CASE
        WHEN failure_count + 1 >= $1 THEN $2
        ELSE cooldown_until
    END,
    updated_at = NOW()
WHERE id = $3
RETURNING id, name, url, topics, secret, active, max_attempts, timeout_ms,
          circuit_state, failure_count, last_failure_at, cooldown_until,
          created_at, updated_at
`

type MarkEndpointDeliveryFailureParams struct {
	FailureThreshold int32              `json:"failure_threshold"`
	CooldownUntil    pgtype.Timestamptz `json:"cooldown_until"`
	ID               uuid.UUID          `json:"id"`
}

func (q *Queries) MarkEndpointDeliveryFailure(ctx context.Context, arg MarkEndpointDeliveryFailureParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, markEndpointDeliveryFailure, arg.FailureThreshold, arg.CooldownUntil, arg.ID)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEndpointDeliverySuccess = `-- name: MarkEndpointDeliverySuccess :one
UPDATE endpoints
SET circuit_state = 'closed',
    failure_count = 0,
    last_failure_at = NULL,
    cooldown_until = NULL,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, url, topics, secret, active, max_attempts, timeout_ms,
          circuit_state, failure_count, last_failure_at, cooldown_until,
          created_at, updated_at
`

func (q *Queries) MarkEndpointDeliverySuccess(ctx context.Context, id uuid.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, markEndpointDeliverySuccess, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const moveEndpointCircuitToHalfOpen = `-- name: MoveEndpointCircuitToHalfOpen :one
UPDATE endpoints
SET circuit_state = 'half_open',
    updated_at = NOW()
WHERE id = $1
  AND circuit_state = 'open'
  AND cooldown_until <= NOW()
RETURNING id, name, url, topics, secret, active, max_attempts, timeout_ms,
          circuit_state, failure_count, last_failure_at, cooldown_until,
          created_at, updated_at
`

func (q *Queries) MoveEndpointCircuitToHalfOpen(ctx context.Context, id uuid.UUID) (Endpoint, error) {
	row := q.db.QueryRow(ctx, moveEndpointCircuitToHalfOpen, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEndpoint = `-- name: UpdateEndpoint :one
UPDATE endpoints
SET name = $1,
    url = $2,
    topics = $3,
    secret = $4,
    active = $5,
    max_attempts = $6,
    timeout_ms = $7,
    updated_at = NOW()
WHERE id = $8
RETURNING id, name, url, topics, secret, active, max_attempts, timeout_ms,
          circuit_state, failure_count, last_failure_at, cooldown_until,
          created_at, updated_at
`

type UpdateEndpointParams struct {
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	Topics      []string    `json:"topics"`
	Secret      pgtype.Text `json:"secret"`
	Active      bool        `json:"active"`
	MaxAttempts int32       `json:"max_attempts"`
	TimeoutMs   int32       `json:"timeout_ms"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error) {
	row := q.db.QueryRow(ctx, updateEndpoint,
		arg.Name,
		arg.Url,
		arg.Topics,
		arg.Secret,
		arg.Active,
		arg.MaxAttempts,
		arg.TimeoutMs,
		arg.ID,
	)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Topics,
		&i.Secret,
		&i.Active,
		&i.MaxAttempts,
		&i.TimeoutMs,
		&i.CircuitState,
		&i.FailureCount,
		&i.LastFailureAt,
		&i.CooldownUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
