// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_management.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (idempotency_key, topic, payload)
VALUES ($1, $2, $3)
RETURNING id, idempotency_key, topic, payload, received_at
`

type CreateEventParams struct {
	IdempotencyKey string `json:"idempotency_key"`
	Topic          string `json:"topic"`
	Payload        []byte `json:"payload"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent, arg.IdempotencyKey, arg.Topic, arg.Payload)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Topic,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, idempotency_key, topic, payload, received_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Topic,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const getEventByIdempotencyKey = `-- name: GetEventByIdempotencyKey :one
SELECT id, idempotency_key, topic, payload, received_at
FROM events
WHERE idempotency_key = $1
`

func (q *Queries) GetEventByIdempotencyKey(ctx context.Context, idempotencyKey string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIdempotencyKey, idempotencyKey)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Topic,
		&i.Payload,
		&i.ReceivedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, idempotency_key, topic, payload, received_at
FROM events
WHERE (
    ($1::timestamptz IS NULL AND $2::uuid IS NULL)
    OR (received_at, id) < ($1::timestamptz, $2::uuid)
)
ORDER BY received_at DESC, id DESC
LIMIT $3
`

type ListEventsParams struct {
	CursorReceivedAt pgtype.Timestamptz `json:"cursor_received_at"`
	CursorID         pgtype.UUID        `json:"cursor_id"`
	Limit            int32              `json:"limit"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.CursorReceivedAt, arg.CursorID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.Topic,
			&i.Payload,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
