// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Delivery struct {
	ID              uuid.UUID          `json:"id"`
	EventID         uuid.UUID          `json:"event_id"`
	EndpointID      uuid.UUID          `json:"endpoint_id"`
	Status          string             `json:"status"`
	AttemptCount    int32              `json:"attempt_count"`
	NextRetryAt     time.Time          `json:"next_retry_at"`
	LastHttpStatus  *int32             `json:"last_http_status"`
	LastError       pgtype.Text        `json:"last_error"`
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	DeadLetteredAt  pgtype.Timestamptz `json:"dead_lettered_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type Endpoint struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	Url           string             `json:"url"`
	Topics        []string           `json:"topics"`
	Secret        pgtype.Text        `json:"secret"`
	Active        bool               `json:"active"`
	MaxAttempts   int32              `json:"max_attempts"`
	TimeoutMs     int32              `json:"timeout_ms"`
	CircuitState  string             `json:"circuit_state"`
	FailureCount  int32              `json:"failure_count"`
	LastFailureAt pgtype.Timestamptz `json:"last_failure_at"`
	CooldownUntil pgtype.Timestamptz `json:"cooldown_until"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type Event struct {
	ID             uuid.UUID `json:"id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Topic          string    `json:"topic"`
	Payload        []byte    `json:"payload"`
	ReceivedAt     time.Time `json:"received_at"`
}
