// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClaimPendingDeliveriesForWorker(ctx context.Context, limit int32) ([]Delivery, error)
	CountPendingDeliveries(ctx context.Context) (int64, error)
	CreateDeliveriesForEvent(ctx context.Context, arg CreateDeliveriesForEventParams) ([]Delivery, error)
	CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error)
	CreateEndpoint(ctx context.Context, arg CreateEndpointParams) (Endpoint, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	DeleteEndpoint(ctx context.Context, id uuid.UUID) error
	GetDeliveryByEventAndEndpoint(ctx context.Context, arg GetDeliveryByEventAndEndpointParams) (Delivery, error)
	GetDeliveryByID(ctx context.Context, id uuid.UUID) (Delivery, error)
	GetEndpointByID(ctx context.Context, id uuid.UUID) (Endpoint, error)
	GetEndpointByName(ctx context.Context, name string) (Endpoint, error)
	GetEventByID(ctx context.Context, id uuid.UUID) (Event, error)
	GetEventByIdempotencyKey(ctx context.Context, idempotencyKey string) (Event, error)
	// Ready pending deliveries for worker queue processing.
	GetPendingDeliveriesForWorker(ctx context.Context, limit int32) ([]Delivery, error)
	ListActiveEndpointsByTopics(ctx context.Context, topics []string) ([]Endpoint, error)
	ListDeadLetteredDeliveries(ctx context.Context, arg ListDeadLetteredDeliveriesParams) ([]Delivery, error)
	ListDeliveriesByEndpoint(ctx context.Context, arg ListDeliveriesByEndpointParams) ([]Delivery, error)
	ListEndpoints(ctx context.Context, arg ListEndpointsParams) ([]Endpoint, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	MarkEndpointDeliveryFailure(ctx context.Context, arg MarkEndpointDeliveryFailureParams) (Endpoint, error)
	MarkEndpointDeliverySuccess(ctx context.Context, id uuid.UUID) (Endpoint, error)
	MoveEndpointCircuitToHalfOpen(ctx context.Context, id uuid.UUID) (Endpoint, error)
	RescheduleDelivery(ctx context.Context, arg RescheduleDeliveryParams) (Delivery, error)
	ResetStaleDelivering(ctx context.Context, staleAfterMilliseconds int64) error
	UpdateDeliveryAttempt(ctx context.Context, arg UpdateDeliveryAttemptParams) (Delivery, error)
	UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) (Endpoint, error)
}

var _ Querier = (*Queries)(nil)
